version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    command: pnpm nx dev api
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../../../apps/api:/app/apps/api
      - ../../../packages:/app/packages
      - ../../../node_modules:/app/node_modules

  web:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    command: pnpm nx dev web
    ports:
      - '3000:3000'
    volumes:
      - ../../../apps/web:/app/apps/web
      - ../../../packages:/app/packages
      - ../../../node_modules:/app/node_modules
