version: '3.8'

services:
  api:
    build:
      context: ../../..
      dockerfile: Dockerfile
      target: runner
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build:
      context: ../../..
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
